/**
 * src/routes/index.tsx
 *
 * Home page — demonstrates end-to-end type-safe data fetching from the
 * Encore.ts backend through the auto-generated client SDK.
 *
 * The Encore CLI generates the client once via:
 *   encore gen client --target=typescript --output=.encore/clients.ts
 *
 * SolidJS's `createResource` keeps the component reactive with zero
 * virtual-DOM overhead: only the exact text node for `display_name` is
 * patched when the data arrives.
 */

import { createResource, Show, Suspense } from "solid-js";
// Auto-generated by `encore gen client` — reflects every exposed API endpoint.
import Client from "~/.encore/clients";

const client = new Client(
  // In production, replace with your deployed Encore environment URL.
  import.meta.env.VITE_ENCORE_BASE_URL ?? "http://localhost:4000"
);

// The email to look up — in a real app this would come from route params or auth context.
const DEMO_EMAIL = "demo@example.com";

async function fetchUser() {
  // `client.users.getUserByEmail` is fully typed: TypeScript knows the shape
  // of the response (UsersTable) without any manual type annotation.
  const user = await client.users.getUserByEmail({ email: DEMO_EMAIL });
  return user;
}

export default function Home() {
  const [user] = createResource(fetchUser);

  return (
    <main>
      <h1>BLAST Stack Demo</h1>
      <Suspense fallback={<p>Loading…</p>}>
        <Show when={user()} fallback={<p>User not found.</p>}>
          {(u) => (
            <p>
              Welcome, <strong>{u().display_name}</strong>!
            </p>
          )}
        </Show>
      </Suspense>
    </main>
  );
}
