/**
 * db.d.ts — Auto-generated TypeScript interfaces derived from the PostgreSQL schema.
 *
 * DO NOT EDIT MANUALLY.
 *
 * Generated by `pg-to-ts` (https://github.com/danvk/pg-to-ts):
 *   npm run gen:types            (runs: pg-to-ts generate -c $DATABASE_URL -o db.d.ts)
 *
 * Re-run this command whenever a new SQL migration is applied so that the
 * TypeScript types stay in sync with the database schema — no ORM, no runtime
 * reflection, zero overhead.
 */

/** Mirrors the `users` table defined in migrations/1_init.up.sql. */
export interface UsersTable {
  /** BIGSERIAL PRIMARY KEY — auto-incremented 64-bit integer. */
  id: string; // pg returns BIGINT as string to avoid JS number precision loss
  /** Unique user e-mail address. Indexed via users_email_key (B-Tree, auto-created by UNIQUE constraint). */
  email: string;
  /** Human-readable display name. */
  display_name: string;
}
